/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoExame;
import fatec.poo.control.DaoMedico;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Exame;
import fatec.poo.model.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author Pasquale
 */
public class GuiMarcarExame extends javax.swing.JFrame {

    /**
     * Creates new form GuiMarcarExame
     */
    public GuiMarcarExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigoConsulta = new javax.swing.JLabel();
        txtCodigoConsulta = new javax.swing.JTextField();
        btnConsultarCodigoConsulta = new javax.swing.JButton();
        lblMedico = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        ftxData = new javax.swing.JFormattedTextField();
        lblHorario = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Marcar Exame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCodigo.setText("Código");

        lblCodigoConsulta.setText("Código Consulta");

        txtCodigoConsulta.setEnabled(false);

        btnConsultarCodigoConsulta.setText("...");
        btnConsultarCodigoConsulta.setEnabled(false);
        btnConsultarCodigoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoConsultaActionPerformed(evt);
            }
        });

        lblMedico.setText("Médico");

        txtMedico.setEnabled(false);

        lblDescricao.setText("Descrição");

        txtDescricao.setEnabled(false);

        lblData.setText("Data");

        try {
            ftxData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxData.setEnabled(false);

        lblHorario.setText("Horário");

        txtHorario.setEnabled(false);

        lblValor.setText("Valor");

        txtValor.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoConsulta)
                    .addComponent(lblCodigo)
                    .addComponent(lblDescricao)
                    .addComponent(lblData)
                    .addComponent(lblHorario)
                    .addComponent(lblValor)
                    .addComponent(btnConsultar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtCodigo))
                        .addGap(27, 27, 27)
                        .addComponent(btnConsultarCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(lblMedico)
                        .addGap(18, 18, 18)
                        .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescricao)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInserir)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(txtHorario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftxData, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(59, 59, 59)
                        .addComponent(btnAlterar)
                        .addGap(47, 47, 47)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoConsulta)
                    .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCodigoConsulta)
                    .addComponent(lblMedico)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //prepCon = new PreparaConexao("BD2321003","BD2321003");
        prepCon = new PreparaConexao("system", "admn1992");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        //prepCon.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");        
        prepCon.setConnectionString("jdbc:oracle:thin:@192.168.0.104:1521:xe");
        daoExame = new DaoExame(prepCon.abrirConexao());
        daoConsulta = new DaoConsulta(prepCon.abrirConexao());
        daoMedico = new DaoMedico(prepCon.abrirConexao());

        txtCodigo.setText("");
        txtCodigoConsulta.setText("");
        txtMedico.setText("");
        txtDescricao.setText("");
        ftxData.setText("");
        txtHorario.setText("");
        txtValor.setText("");

        txtCodigo.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);;
        txtMedico.setEnabled(false);;
        txtDescricao.setEnabled(false);;
        ftxData.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtCodigo.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codigo;
        
        try {
            codigo = Integer.parseInt(txtCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código do Exame inválido. Informe um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            txtCodigo.setText("");
            txtCodigo.requestFocus();
            return;
        }

        exame = daoExame.consultar(codigo);

        if (exame != null) {
            txtCodigoConsulta.setText(String.valueOf(exame.getConsulta().getCodigo())); //
            txtMedico.setText(exame.getConsulta().getMedico().getNome());
            txtDescricao.setText(exame.getDescricao());
            ftxData.setText(exame.getData());
            txtHorario.setText(exame.getHorario());
            txtValor.setText(String.valueOf(exame.getValor()));

            txtCodigo.setEnabled(false);
            txtCodigoConsulta.setEnabled(false);;
            txtMedico.setEnabled(false);;
            txtDescricao.setEnabled(true);;
            ftxData.setEnabled(true);
            txtHorario.setEnabled(true);
            txtValor.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);

            txtCodigoConsulta.requestFocus();

        } else {
            JOptionPane.showMessageDialog(this, "Exame não cadastrado. Prossiga com a inserção de dados.", "Informação", JOptionPane.INFORMATION_MESSAGE);

            txtCodigoConsulta.setText("");
            txtMedico.setText("");
            txtDescricao.setText("");
            ftxData.setText("");
            txtHorario.setText("");
            txtValor.setText("");

            txtCodigo.setEnabled(false);
            txtCodigoConsulta.setEnabled(true);;
            txtMedico.setEnabled(false);;
            txtDescricao.setEnabled(false);;
            ftxData.setEnabled(false);
            txtHorario.setEnabled(false);
            txtValor.setEnabled(false);

            btnConsultar.setEnabled(false);
            btnConsultarCodigoConsulta.setEnabled(true);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            txtCodigoConsulta.requestFocus();
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultarCodigoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoConsultaActionPerformed
        int codigo;

        try {
            codigo = Integer.parseInt(txtCodigoConsulta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código da consulta inválido. Informe um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            txtCodigoConsulta.setText("");
            txtCodigoConsulta.requestFocus();
            return;
        }

        consulta = daoConsulta.consultar(codigo);
        //exame = daoExame.consultar(codigo);

        if (consulta == null) {
            JOptionPane.showMessageDialog(null, "Consulta não cadastrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtMedico.setText("");
            txtMedico.requestFocus();
        } else {
            txtMedico.setText(consulta.getMedico().getNome());
            txtCodigoConsulta.setEnabled(false);
            btnConsultarCodigoConsulta.setEnabled(false);

            txtDescricao.setEnabled(true);
            ftxData.setEnabled(true);
            txtHorario.setEnabled(true);
            txtValor.setEnabled(true);

            txtDescricao.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarCodigoConsultaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        int codigo;

        try {
            codigo = Integer.parseInt(txtCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código do Exame inválido. Informe um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            txtCodigo.setText("");
            txtCodigo.requestFocus();
            return;
        }

        exame = new Exame(codigo, txtDescricao.getText());
        exame.setData(ftxData.getText());
        exame.setHorario(txtHorario.getText());
        exame.setValor(Double.parseDouble(txtValor.getText().replace(",",".")));
        exame.setConsulta(consulta);

        daoExame.inserir(exame);
        JOptionPane.showMessageDialog(this, "Exame inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        txtCodigo.setText("");
        txtCodigoConsulta.setText("");
        txtMedico.setText("");
        txtDescricao.setText("");
        ftxData.setText("");
        txtHorario.setText("");
        txtValor.setText("");

        txtCodigo.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);;
        txtMedico.setEnabled(false);;
        txtDescricao.setEnabled(false);;
        ftxData.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtCodigo.requestFocus();

        exame = null;
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração dos Dados do Exame?") == 0) {
            String novaDescricao = txtDescricao.getText();
            String novaData = ftxData.getText();
            String novoHorario = txtHorario.getText();
            double novoValor;

            if (novaDescricao.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "A descrição não pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtDescricao.requestFocus();
            } else if (novaData.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "A data não pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                ftxData.requestFocus();
            } else if (novoHorario.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O horário não pode estar vazio.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtHorario.requestFocus();
            }

            try {
                if (txtValor.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Quantidade de dias pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                    txtValor.requestFocus();
                    return;
                }
                novoValor = Double.parseDouble(txtValor.getText());

                if (novoValor < 0) {
                    JOptionPane.showMessageDialog(this, "Valor não pode ser negativo.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                    txtValor.requestFocus();
                    return;
                }
                exame.setValor(novoValor);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor inválido para exame. Use números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtValor.requestFocus();
                return;
            }

            exame.setData(novaData);
            exame.setHorario(novoHorario);

            daoExame.alterar(exame);
            JOptionPane.showMessageDialog(this, "Dados do exame alterados com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
        txtCodigo.setText("");
        txtCodigoConsulta.setText("");
        txtMedico.setText("");
        txtDescricao.setText("");
        ftxData.setText("");
        txtHorario.setText("");
        txtValor.setText("");

        txtCodigo.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);;
        txtMedico.setEnabled(false);;
        txtDescricao.setEnabled(false);;
        ftxData.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtCodigo.requestFocus();

        exame = null;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão dos dados do Exame?") == 0) {
            daoExame.excluir(exame);
            JOptionPane.showMessageDialog(this, "Exame excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            txtCodigo.setText("");
            txtCodigoConsulta.setText("");
            txtMedico.setText("");
            txtDescricao.setText("");
            ftxData.setText("");
            txtHorario.setText("");
            txtValor.setText("");

            txtCodigo.setEnabled(true);
            txtCodigoConsulta.setEnabled(false);;
            txtMedico.setEnabled(false);;
            txtDescricao.setEnabled(false);;
            ftxData.setEnabled(false);
            txtHorario.setEnabled(false);
            txtValor.setEnabled(false);

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            txtCodigo.requestFocus();

            exame = null;
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    private PreparaConexao prepCon;
    private DaoConsulta daoConsulta;
    private DaoMedico daoMedico;
    private DaoExame daoExame;
    private Consulta consulta;
    private Medico medico;
    private Exame exame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCodigoConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftxData;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoConsulta;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoConsulta;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
