/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoMedico;
import fatec.poo.control.DaoPaciente;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Medico;
import fatec.poo.model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author Pasquale
 */
public class GuiMarcarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form GuiMarcarConsulta
     */
    public GuiMarcarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblCPFMedico = new javax.swing.JLabel();
        lblCPFPaciente = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        ftxCPFMedico = new javax.swing.JFormattedTextField();
        ftxCPFPaciente = new javax.swing.JFormattedTextField();
        ftxData = new javax.swing.JFormattedTextField();
        txtValor = new javax.swing.JTextField();
        btnBuscarCPFMedico = new javax.swing.JButton();
        txtNomeMedico = new javax.swing.JTextField();
        btnBuscarCPFPaciente = new javax.swing.JButton();
        txtNomePaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Marcar Consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCodigo.setText("Código");

        lblCPFMedico.setText("CPF Médico");

        lblCPFPaciente.setText("CPF Paciente");

        lblData.setText("Data");

        lblValor.setText("Valor");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            ftxCPFMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPFMedico.setEnabled(false);

        try {
            ftxCPFPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPFPaciente.setEnabled(false);

        try {
            ftxData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxData.setEnabled(false);

        txtValor.setEnabled(false);

        btnBuscarCPFMedico.setText("...");
        btnBuscarCPFMedico.setEnabled(false);
        btnBuscarCPFMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCPFMedicoActionPerformed(evt);
            }
        });

        txtNomeMedico.setEnabled(false);

        btnBuscarCPFPaciente.setText("...");
        btnBuscarCPFPaciente.setEnabled(false);
        btnBuscarCPFPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCPFPacienteActionPerformed(evt);
            }
        });

        txtNomePaciente.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor)
                    .addComponent(lblData)
                    .addComponent(lblCPFPaciente)
                    .addComponent(lblCPFMedico)
                    .addComponent(lblCodigo))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addGap(38, 38, 38)
                                .addComponent(btnInserir)
                                .addGap(39, 39, 39)
                                .addComponent(btnAlterar)
                                .addGap(43, 43, 43)))
                        .addComponent(btnExcluir)
                        .addGap(61, 61, 61)
                        .addComponent(btnSair)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxCPFMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxCPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarCPFMedico)
                            .addComponent(btnBuscarCPFPaciente))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeMedico)
                            .addComponent(txtNomePaciente))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFMedico)
                    .addComponent(ftxCPFMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCPFMedico)
                    .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFPaciente)
                    .addComponent(ftxCPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCPFPaciente)
                    .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //prepCon = new PreparaConexao("BD2321003","BD2321003");
        prepCon = new PreparaConexao("system", "admn1992");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        //prepCon.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");        
        prepCon.setConnectionString("jdbc:oracle:thin:@192.168.0.104:1521:xe");
        daoConsulta = new DaoConsulta(prepCon.abrirConexao());

        daoPaciente = new DaoPaciente(prepCon.abrirConexao());
        daoMedico = new DaoMedico(prepCon.abrirConexao());

        txtCodigo.setText("");
        ftxCPFMedico.setText("");
        ftxCPFPaciente.setText("");
        txtNomeMedico.setText("");
        txtNomePaciente.setText("");
        ftxData.setText("");
        txtValor.setText("");

        txtCodigo.setEnabled(true);
        ftxCPFMedico.setEnabled(false);
        ftxCPFPaciente.setEnabled(false);
        ftxData.setEnabled(false);
        txtValor.setEnabled(false);
        txtNomeMedico.setEnabled(false);
        txtNomePaciente.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtCodigo.requestFocus();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codigo;

        try {
            codigo = Integer.parseInt(txtCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código da Consulta inválido. Informe um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            txtCodigo.setText("");
            txtCodigo.requestFocus();
            return;
        }

        consulta = daoConsulta.consultar(codigo);
        paciente = null;

        if (consulta != null) {

            ftxCPFMedico.setText(consulta.getMedico().getCpf());
            txtNomeMedico.setText(consulta.getMedico().getNome());

            String cpfPaciente = consulta.getCpfPaciente();
            paciente = daoPaciente.consultar(cpfPaciente);

            
            ftxCPFPaciente.setText(paciente.getCpf());
            txtNomePaciente.setText(paciente.getNome());

            ftxData.setText(consulta.getData());
            txtValor.setText(String.valueOf(consulta.getValor()));

            txtCodigo.setEnabled(false);
            ftxCPFMedico.setEnabled(false);
            ftxCPFPaciente.setEnabled(false);
            ftxData.setEnabled(true);
            txtValor.setEnabled(true);
            txtNomeMedico.setEnabled(false);
            txtNomePaciente.setEnabled(false);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);

            ftxCPFMedico.requestFocus();

        } else {
            JOptionPane.showMessageDialog(this, "Consulta não cadastrada. Prossiga com a inserção de dados.", "Informação", JOptionPane.INFORMATION_MESSAGE);

            ftxCPFMedico.setText("");
            ftxCPFPaciente.setText("");
            txtNomeMedico.setText("");
            txtNomePaciente.setText("");
            ftxData.setText("");
            txtValor.setText("");

            txtCodigo.setEnabled(false);
            ftxCPFMedico.setEnabled(true);
            ftxCPFPaciente.setEnabled(false);
            ftxData.setEnabled(true);
            txtValor.setEnabled(true);
            txtNomeMedico.setEnabled(false);
            txtNomePaciente.setEnabled(false);

            btnConsultar.setEnabled(false);
            btnBuscarCPFMedico.setEnabled(true);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            ftxCPFMedico.requestFocus();

        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnBuscarCPFMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCPFMedicoActionPerformed
        String cpfFormatado = ftxCPFMedico.getText();
        String cpfNumeros = cpfFormatado.replaceAll("[^0-9]", "");

        if (!medico.validarCPF(cpfNumeros)) {
            JOptionPane.showMessageDialog(this, "CPF inválido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);

            ftxCPFMedico.setEnabled(true);
            ftxCPFMedico.requestFocus();

            return;
        }

        medico = daoMedico.consultar(cpfNumeros);

        if (medico == null) {
            JOptionPane.showMessageDialog(null, "Médico não cadastrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            ftxCPFMedico.setText("");
            ftxCPFMedico.requestFocus();
        } else {
            txtNomeMedico.setText(medico.getNome());

            ftxCPFMedico.setEnabled(false);
            btnBuscarCPFMedico.setEnabled(false);

            ftxCPFPaciente.setEnabled(true);
            btnBuscarCPFPaciente.setEnabled(true);
            ftxCPFPaciente.requestFocus();
        }


    }//GEN-LAST:event_btnBuscarCPFMedicoActionPerformed

    private void btnBuscarCPFPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCPFPacienteActionPerformed
        String cpfFormatado = ftxCPFPaciente.getText();
        String cpfNumeros = cpfFormatado.replaceAll("[^0-9]", "");

        if (!paciente.validarCPF(cpfNumeros)) {
            JOptionPane.showMessageDialog(this, "CPF inválido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);

            ftxCPFPaciente.setEnabled(true);
            ftxCPFPaciente.requestFocus();

            return;
        }

        paciente = daoPaciente.consultar(cpfNumeros);

        if (paciente == null) {
            JOptionPane.showMessageDialog(null, "Paciente não cadastrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            ftxCPFPaciente.setText("");
            ftxCPFPaciente.requestFocus();
        } else {
            txtNomePaciente.setText(paciente.getNome());

            ftxCPFPaciente.setEnabled(false);
            btnBuscarCPFPaciente.setEnabled(false);

            ftxData.setEnabled(true);
            txtValor.setEnabled(true);

            btnInserir.setEnabled(true);
            ftxData.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarCPFPacienteActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        int codigo;
        String cpfPaciente = ftxCPFPaciente.getText().replaceAll("[^0-9]", "");
        String data = ftxData.getText();
        String valorText = txtValor.getText();
        Double valor;

        if (cpfPaciente == null || !paciente.validarCPF(cpfPaciente)) {
            JOptionPane.showMessageDialog(this, "CPF inválido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);

            ftxCPFPaciente.setEnabled(true);
            ftxCPFPaciente.requestFocus();

            return;
        }

        try {
            codigo = Integer.parseInt(txtCodigo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtCodigo.requestFocus();
            return;
        }

        if (data.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data não pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            ftxData.requestFocus();
            return;
        }

        try {
            valor = Double.parseDouble(txtValor.getText().replace(",", "."));
            if (valor < 0) {
                JOptionPane.showMessageDialog(this, "Valor não pode ser negativo.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtValor.requestFocus();
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor inválido para consulta.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            txtValor.requestFocus();
            return;
        }

        consulta = new Consulta(codigo, data);
        consulta.setValor(valor);
        consulta.setMedico(medico);

        paciente.addConsultas(consulta);

        daoConsulta.inserir(consulta, cpfPaciente);
        JOptionPane.showMessageDialog(this, "Consulta inserida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        txtCodigo.setText("");
        ftxCPFMedico.setText("");
        ftxCPFPaciente.setText("");
        txtNomeMedico.setText("");
        txtNomePaciente.setText("");
        ftxData.setText("");
        txtValor.setText("");

        txtCodigo.setEnabled(true);
        ftxCPFMedico.setEnabled(false);
        ftxCPFPaciente.setEnabled(false);
        ftxData.setEnabled(false);
        txtValor.setEnabled(false);
        txtNomeMedico.setEnabled(false);
        txtNomePaciente.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtCodigo.requestFocus();

        consulta = null;
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração dos Dados do Hóspede?") == 0) {
            String novaData = ftxData.getText();
            String cpfPaciente = ftxCPFPaciente.getText().replaceAll("[^0-9]", "");
            Double novoValor;

            if (novaData.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "A data não pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                ftxData.requestFocus();
            }

            try {
                if (txtValor.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Valor não pode estar vazio.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                    txtValor.requestFocus();
                    return;
                }

                novoValor = Double.parseDouble(txtValor.getText().replace(",", "."));
                if (novoValor < 0) {
                    JOptionPane.showMessageDialog(this, "Valor não pode ser negativo.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                    txtValor.requestFocus();
                    return;
                }
                consulta.setValor(novoValor);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor inválido para consulta. Use números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtValor.requestFocus();
                return;
            }

            consulta.setData(novaData);

            daoConsulta.alterar(consulta, cpfPaciente);
            JOptionPane.showMessageDialog(this, "Dados da consulta alterados com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }

        txtCodigo.setText("");
        ftxCPFMedico.setText("");
        ftxCPFPaciente.setText("");
        txtNomeMedico.setText("");
        txtNomePaciente.setText("");
        ftxData.setText("");
        txtValor.setText("");

        txtCodigo.setEnabled(true);
        ftxCPFMedico.setEnabled(false);
        ftxCPFPaciente.setEnabled(false);
        ftxData.setEnabled(false);
        txtValor.setEnabled(false);
        txtNomeMedico.setEnabled(false);
        txtNomePaciente.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtCodigo.requestFocus();

        consulta = null;

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão dos dados da Consulta?") == 0) {
            daoConsulta.excluir(consulta);
            JOptionPane.showMessageDialog(this, "Consulta excluída com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            txtCodigo.setText("");
            ftxCPFMedico.setText("");
            ftxCPFPaciente.setText("");
            txtNomeMedico.setText("");
            txtNomePaciente.setText("");
            ftxData.setText("");
            txtValor.setText("");

            txtCodigo.setEnabled(true);
            ftxCPFMedico.setEnabled(false);
            ftxCPFPaciente.setEnabled(false);
            ftxData.setEnabled(false);
            txtValor.setEnabled(false);
            txtNomeMedico.setEnabled(false);
            txtNomePaciente.setEnabled(false);

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            txtCodigo.requestFocus();

            consulta = null;
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private PreparaConexao prepCon;
    private DaoConsulta daoConsulta;
    private DaoPaciente daoPaciente;
    private DaoMedico daoMedico;
    private Consulta consulta;
    private Medico medico;
    private Paciente paciente;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarCPFMedico;
    private javax.swing.JButton btnBuscarCPFPaciente;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftxCPFMedico;
    private javax.swing.JFormattedTextField ftxCPFPaciente;
    private javax.swing.JFormattedTextField ftxData;
    private javax.swing.JLabel lblCPFMedico;
    private javax.swing.JLabel lblCPFPaciente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
