/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoMedicacao;
import fatec.poo.control.DaoMedico;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Medicacao;
import fatec.poo.model.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author Pasquale
 */
public class GuiPrescreverMedicacao extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrescreverMedicacao
     */
    public GuiPrescreverMedicacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCodigoConsulta = new javax.swing.JLabel();
        lblDosagem = new javax.swing.JLabel();
        lblDosagemDias = new javax.swing.JLabel();
        txtCodigoConsulta = new javax.swing.JTextField();
        txtDosagem = new javax.swing.JTextField();
        txtQtdDias = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnConsultarCodigoConsulta = new javax.swing.JButton();
        lblMedico = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prescrever Medicação");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNome.setText("Nome");

        lblCodigoConsulta.setText("Código Consulta");

        lblDosagem.setText("Dosagem");

        lblDosagemDias.setText("Quantidade Dias");

        txtCodigoConsulta.setEnabled(false);

        txtDosagem.setEnabled(false);

        txtQtdDias.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultarCodigoConsulta.setText("...");
        btnConsultarCodigoConsulta.setEnabled(false);
        btnConsultarCodigoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoConsultaActionPerformed(evt);
            }
        });

        lblMedico.setText("Médico");

        txtMedico.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoConsulta)
                            .addComponent(lblDosagem)
                            .addComponent(lblNome)
                            .addComponent(lblDosagemDias))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDosagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtdDias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserir)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultarCodigoConsulta)
                        .addGap(41, 41, 41)
                        .addComponent(lblMedico)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoConsulta)
                    .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCodigoConsulta)
                    .addComponent(lblMedico)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDosagem)
                    .addComponent(txtDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDosagemDias)
                    .addComponent(txtQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //prepCon = new PreparaConexao("BD2321003","BD2321003");
        prepCon = new PreparaConexao("system", "admn1992");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        //prepCon.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");        
        prepCon.setConnectionString("jdbc:oracle:thin:@192.168.0.104:1521:xe");
        daoMedicacao = new DaoMedicacao(prepCon.abrirConexao());
        daoConsulta = new DaoConsulta(prepCon.abrirConexao());
        daoMedico = new DaoMedico(prepCon.abrirConexao());

        txtNome.setText("");
        txtCodigoConsulta.setText("");
        txtMedico.setText("");
        txtDosagem.setText("");
        txtQtdDias.setText("");

        txtNome.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);
        txtMedico.setEnabled(false);
        txtDosagem.setEnabled(false);
        txtQtdDias.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtNome.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String nomeMedicacao = txtNome.getText();

        if (nomeMedicacao.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome inválido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            txtNome.setEnabled(true);
            txtNome.requestFocus();
            return;
        }

        medicacao = daoMedicacao.consultar(nomeMedicacao);
        consulta = null;

        if (medicacao != null) {
            int codConsulta = medicacao.getCodigoConsulta();

            consulta = daoConsulta.consultar(codConsulta);

            if (consulta != null) {
                txtCodigoConsulta.setText(String.valueOf(consulta.getCodigo()));
                txtMedico.setText(consulta.getMedico().getNome());

            } else {
                txtCodigoConsulta.setText("");
                txtMedico.setText("");
            }

            txtDosagem.setText(medicacao.getDosagem());
            txtQtdDias.setText(String.valueOf(medicacao.getQtdeDias()));

            txtNome.setEnabled(false);
            txtCodigoConsulta.setEnabled(false);
            txtMedico.setEnabled(false);
            txtDosagem.setEnabled(true);
            txtQtdDias.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);

            txtCodigoConsulta.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Medicação não cadastrada. Prossiga com a inserção de dados.", "Informação", JOptionPane.INFORMATION_MESSAGE);

            txtCodigoConsulta.setText("");
            txtMedico.setText("");
            txtDosagem.setText("");
            txtQtdDias.setText("");

            txtNome.setEnabled(false);
            txtCodigoConsulta.setEnabled(true);
            txtMedico.setEnabled(false);
            txtDosagem.setEnabled(false);
            txtQtdDias.setEnabled(false);

            btnConsultar.setEnabled(false);
            btnConsultarCodigoConsulta.setEnabled(true);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            txtCodigoConsulta.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultarCodigoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoConsultaActionPerformed
        int codigo;

        try {
            codigo = Integer.parseInt(txtCodigoConsulta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código da consulta inválido. Informe um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            txtCodigoConsulta.setText("");
            txtCodigoConsulta.requestFocus();
            return;
        }

        consulta = daoConsulta.consultar(codigo);

        if (consulta == null) {
            JOptionPane.showMessageDialog(null, "Consulta não cadastrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtMedico.setText("");
            txtMedico.requestFocus();
        } else {
            txtMedico.setText(consulta.getMedico().getNome());
            txtCodigoConsulta.setEnabled(false);
            btnConsultarCodigoConsulta.setEnabled(false);

            txtDosagem.setEnabled(true);
            txtQtdDias.setEnabled(true);

            btnInserir.setEnabled(true);

            txtDosagem.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarCodigoConsultaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String nome = txtNome.getText();
        int codigoConsulta;

        if (nome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome inválido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            txtNome.setEnabled(true);
            txtNome.requestFocus();
            return;
        }

        try {
            codigoConsulta = Integer.parseInt(txtCodigoConsulta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código de Consulta inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtCodigoConsulta.requestFocus();
            return;
        }

        medicacao = new Medicacao(nome);
        medicacao.setDosagem(txtDosagem.getText());
        medicacao.setQtdeDias(Integer.parseInt(txtQtdDias.getText()));
        consulta.addMedicacoes(medicacao);

        daoMedicacao.inserir(medicacao, codigoConsulta);
        JOptionPane.showMessageDialog(this, "Consulta inserida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        txtNome.setText("");
        txtCodigoConsulta.setText("");
        txtMedico.setText("");
        txtDosagem.setText("");
        txtQtdDias.setText("");

        txtNome.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);
        txtMedico.setEnabled(false);
        txtDosagem.setEnabled(false);
        txtQtdDias.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnConsultarCodigoConsulta.setEnabled(false);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtNome.requestFocus();

        medicacao = null;

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração dos Dados da Medicação?") == 0) {
            String novaDosagem = txtDosagem.getText();
            int novaQtdDias;

            if (novaDosagem.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "A dosagem não pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtDosagem.requestFocus();
            }

            try {
                if (txtQtdDias.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Quantidade de dias pode estar vazia.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                    txtQtdDias.requestFocus();
                    return;
                }
                novaQtdDias = Integer.parseInt(txtQtdDias.getText());

                if (novaQtdDias < 0) {
                    JOptionPane.showMessageDialog(this, "Quantidade de dias não pode ser negativa.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                    txtQtdDias.requestFocus();
                    return;
                }
                medicacao.setQtdeDias(novaQtdDias);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantidade de dias inválida para medicação. Use números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                txtQtdDias.requestFocus();
                return;
            }

            medicacao.setDosagem(novaDosagem);
            int codigoConsulta = Integer.parseInt(txtCodigoConsulta.getText());

            daoMedicacao.alterar(medicacao, codigoConsulta);
            JOptionPane.showMessageDialog(this, "Dados da medicação alterados com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }

        txtNome.setText("");
        txtCodigoConsulta.setText("");
        txtMedico.setText("");
        txtDosagem.setText("");
        txtQtdDias.setText("");

        txtNome.setEnabled(true);
        txtCodigoConsulta.setEnabled(false);
        txtMedico.setEnabled(false);
        txtDosagem.setEnabled(false);
        txtQtdDias.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnConsultarCodigoConsulta.setEnabled(false);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        txtNome.requestFocus();

        medicacao = null;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão dos dados da Medicação?") == 0) {
            daoMedicacao.excluir(medicacao);
            JOptionPane.showMessageDialog(this, "Medicação excluída com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            txtNome.setText("");
            txtCodigoConsulta.setText("");
            txtMedico.setText("");
            txtDosagem.setText("");
            txtQtdDias.setText("");

            txtNome.setEnabled(true);
            txtCodigoConsulta.setEnabled(false);
            txtMedico.setEnabled(false);
            txtDosagem.setEnabled(false);
            txtQtdDias.setEnabled(false);

            btnConsultar.setEnabled(true);
            btnConsultarCodigoConsulta.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            txtNome.requestFocus();

            medicacao = null;
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    private PreparaConexao prepCon;
    private DaoConsulta daoConsulta;
    private DaoMedico daoMedico;
    private DaoMedicacao daoMedicacao;
    private Consulta consulta;
    private Medico medico;
    private Medicacao medicacao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCodigoConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCodigoConsulta;
    private javax.swing.JLabel lblDosagem;
    private javax.swing.JLabel lblDosagemDias;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCodigoConsulta;
    private javax.swing.JTextField txtDosagem;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdDias;
    // End of variables declaration//GEN-END:variables
}
