/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatec.poo.view;

import fatec.poo.control.DaoHospede;
import fatec.poo.control.DaoQuarto;
import fatec.poo.control.DaoRecepcionista;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Registro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import fatec.poo.control.DaoRegistro;
import fatec.poo.model.Hospede;
import fatec.poo.model.Quarto;
import fatec.poo.model.Recepcionista;
/**
 *
 * @author Pasquale
 */
public class GuiRegistro extends javax.swing.JFrame {

    /**
     * Creates new form GuiRegistro
     */
    public GuiRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtReg = new javax.swing.JTextField();
        txtNQuarto = new javax.swing.JTextField();
        ftxCPF = new javax.swing.JFormattedTextField();
        ftxDataE = new javax.swing.JFormattedTextField();
        ftxDataS = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        lblValHospedagem = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnPesquisaReg = new javax.swing.JButton();
        btnPesquisaCPF = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPesquisaSituacao = new javax.swing.JButton();
        lblReg = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Hospedagem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Registro Funcional");

        jLabel3.setText("CPF Hóspede");

        jLabel4.setText("Nº Quarto");

        jLabel5.setText("Data entrada");

        jLabel6.setText("Data saída");

        txtReg.setEnabled(false);

        txtNQuarto.setEnabled(false);

        ftxCPF.setEnabled(false);

        ftxDataE.setEnabled(false);

        ftxDataS.setEnabled(false);

        jLabel7.setText("Valor Hospedagem");

        lblValHospedagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnPesquisaReg.setText("...");
        btnPesquisaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaRegActionPerformed(evt);
            }
        });

        btnPesquisaCPF.setText("...");
        btnPesquisaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCPFActionPerformed(evt);
            }
        });

        jLabel9.setText("Situação");

        btnPesquisaSituacao.setText("...");
        btnPesquisaSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaSituacaoActionPerformed(evt);
            }
        });

        lblReg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblCPF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblSituacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxDataS)
                            .addComponent(ftxDataE)
                            .addComponent(ftxCPF)
                            .addComponent(txtNQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValHospedagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(btnPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnReservar)
                                .addGap(43, 43, 43)
                                .addComponent(btnLiberar)
                                .addGap(49, 49, 49)
                                .addComponent(btnSair)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblReg, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPesquisaSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisaReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisaCPF)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(btnPesquisaSituacao)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftxDataE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftxDataS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblValHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnLiberar)
                    .addComponent(btnSair))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepcon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepcon = new PreparaConexao("BD2321003","BD2321003");
        prepcon.setDriver("oracle.jdbc.driver.OracleDriver");
        prepcon.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");
        daoRegistro = new DaoRegistro(prepcon.abrirConexao());
        
       txtReg.setEnabled(true);
       lblCPF.setEnabled(false);
       txtNQuarto.setEnabled(false);
       ftxDataE.setEnabled(false);
       ftxDataS.setEnabled(false);
       lblValHospedagem.setEnabled(false);
       
       btnConsultar.setEnabled(true);
       btnReservar.setEnabled(false);
       btnLiberar.setEnabled(false);
       btnPesquisaReg.setEnabled(false);
       btnPesquisaCPF.setEnabled(false);
       btnPesquisaSituacao.setEnabled(false);
       btnSair.setEnabled(true);
       txtReg.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        //reservado
        registro.reservarQuarto(hospede, quarto);
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        //reservado
        registro.liberarQuarto();
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codigo;
        
        try{
            if(txtCodigo.getText().trim().isEmpty()){
                JOptionPane.showConfirmDialog(this, "Codigo de registro deve ser informado.", 
                        "Atencao", JOptionPane.WARNING_MESSAGE);
                txtCodigo.requestFocus();
                return;
            }
            codigo = Integer.parseInt(txtCodigo.getText());
        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, 
                "Código de registro invalido! Informe um valor numérico inteiro.",
                "Erro de entrada", JOptionPane.ERROR_MESSAGE);
        txtCodigo.requestFocus();
        return;
        
       }
       registro = daoRegistro.consultar(codigo);
       
       if(registro != null){
           
           //validação registro funcional
           try{
                if(txtReg.getText().trim().isEmpty()){
                     JOptionPane.showConfirmDialog(this, "Data de registro deve ser informada.", 
                             "Atencao", JOptionPane.WARNING_MESSAGE);
                   txtReg.setEnabled(true);
                   btnConsultar.setEnabled(false);
                   btnPesquisaReg.setEnabled(true);
                   btnReservar.setEnabled(true);
                     txtReg.requestFocus();
                     return;
                 }
            txtReg.setText(String.valueOf(registro.getRecepcionista().getRegFunc()));
            
           
           }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, 
                 "Registro Funcional Inválido! Informe um valor de inteiro correto.",
                     "Erro de entrada", JOptionPane.ERROR_MESSAGE);
             txtReg.requestFocus();
             return;
           }

           //validação data de saída
           try{
                if(ftxDataS.getText().trim().isEmpty()){
                     JOptionPane.showConfirmDialog(this, "Data de saída deve ser informada.", 
                             "Atencao", JOptionPane.WARNING_MESSAGE);
                     ftxDataS.requestFocus();
                     return;
                 }
               ftxDataS.setText(String.valueOf(registro.getDataEntrada()));

                //Se data Saída for nulo
               if(ftxDataS == null){
                   ftxDataS.setEnabled(true);
                   btnLiberar.setEnabled(true);
                   ftxDataS.requestFocus();
               }
           
           }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, 
                 "Data inválida! Informe um valor de data correto.",
                     "Erro de entrada", JOptionPane.ERROR_MESSAGE);
             ftxDataS.requestFocus();
             return;
           }
           
           ftxCPF.setText(registro.getHospede().getCpf());
           txtNQuarto.setText(String.valueOf(registro.getQuarto().getNumero()));
           ftxDataE.setText(String.valueOf(registro.getDataSaida()));

       }
       //n sei se é o correto/bastante, 
       registros.add(registro);
       
       txtReg.setEnabled(false);
       ftxCPF.setEnabled(true);
       txtNQuarto.setEnabled(true);
       ftxDataE.setEnabled(true);
       ftxDataS.setEnabled(true);
       lblValHospedagem.setEnabled(true);
       
       btnConsultar.setEnabled(false);
       btnReservar.setEnabled(true);
       btnLiberar.setEnabled(true);
       //btnPesquisaReg.setEnabled(true);
       //btnPesquisaCPF.setEnabled(true);
       //btnPesquisaSituacao.setEnabled(true);
       btnSair.setEnabled(true);
       txtReg.requestFocus();
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnPesquisaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaRegActionPerformed
        recepcionista = new DaoRecepcionista(prepcon.abrirConexao()).consultar(Integer.parseInt(txtCodigo.getText()));
        
            //TO_DO try catch com mensagem
        try{
            if(recepcionista == null){
                JOptionPane.showConfirmDialog(this, "Recepcionista não cadastrado!", 
                "Atencao", JOptionPane.WARNING_MESSAGE);
                lblReg.setText("Recepcionista não cadastrado.");
            
                txtReg.setEnabled(true);
                ftxCPF.setEnabled(false);
                btnPesquisaReg.setEnabled(true);
                btnPesquisaCPF.setEnabled(false);
                txtCodigo.requestFocus();
                return;
            }else{
                txtReg.setText(String.valueOf(recepcionista.getRegFunc()));//instancia de recepcionista na GUI
                lblReg.setText(recepcionista.getNome());
                txtNQuarto.setText(String.valueOf(registro.getQuarto().getNumero()));
                ftxDataE.setText(String.valueOf(registro.getDataEntrada()));
                ftxDataS.setText(String.valueOf(registro.getDataSaida()));

                txtReg.setEnabled(false);
                ftxCPF.setEnabled(true);
                btnPesquisaReg.setEnabled(false);
                btnPesquisaCPF.setEnabled(true);
            }
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, 
                "Registro invalido! Informe um valor numérico inteiro.",
                "Erro de entrada", JOptionPane.ERROR_MESSAGE);
                txtCodigo.requestFocus();
                return;
         }

    }//GEN-LAST:event_btnPesquisaRegActionPerformed

    private void btnPesquisaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCPFActionPerformed
        hospede = new DaoHospede(prepcon.abrirConexao()).consultar((txtCodigo.getText()));
        
        try{
            if(hospede == null){
                JOptionPane.showConfirmDialog(this, "Hóspede não cadastrado!", 
                        "Atencao", JOptionPane.WARNING_MESSAGE);
            
                lblCPF.setText("Hóspede não cadastrado");
            
                ftxCPF.setEnabled(true);
                txtNQuarto.setEnabled(false);
                btnPesquisaCPF.setEnabled(true);
                btnPesquisaSituacao.setEnabled(false);
            }else{
                lblCPF.setText(hospede.getNome()); //instancia CPF na label
                ftxCPF.setText(hospede.getCpf());
                txtNQuarto.setText(String.valueOf(registro.getQuarto().getNumero()));
                ftxDataE.setText(String.valueOf(registro.getDataEntrada()));
                ftxDataS.setText(String.valueOf(registro.getDataSaida()));

                ftxCPF.setEnabled(false);
                txtNQuarto.setEnabled(true);
                btnPesquisaCPF.setEnabled(false);
                btnPesquisaSituacao.setEnabled(true);
            
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, 
                "CPF invalido! Informe um valor de texto inteiro.",
                "Erro de entrada", JOptionPane.ERROR_MESSAGE);
                txtCodigo.requestFocus();
                return;
         }
            
    }//GEN-LAST:event_btnPesquisaCPFActionPerformed

    private void btnPesquisaSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaSituacaoActionPerformed
        quarto = new DaoQuarto(prepcon.abrirConexao()).consultar(Integer.parseInt(txtCodigo.getText()));
        
        try{
            if(quarto == null){
                JOptionPane.showConfirmDialog(this, "Quarto não cadastrado!", 
                        "Atencao", JOptionPane.WARNING_MESSAGE);
            
                lblSituacao.setText("Quarto não cadastrado");

                txtNQuarto.setEnabled(true);
                ftxDataE.setEnabled(false);
                ftxDataS.setEnabled(false);
                btnReservar.setEnabled(false);
                btnLiberar.setEnabled(false);
            
            }else{
                if(!quarto.getSituacao()){ //false está livre
                    lblSituacao.setText("Quarto livre!");
                    ftxDataE.setEnabled(true);
                    ftxDataS.setEnabled(false);
                    btnReservar.setEnabled(true);
                    btnLiberar.setEnabled(false);

                }else{ //está reservado
                    lblSituacao.setText("Quarto reservado!");

                    txtNQuarto.setEnabled(true);
                    ftxDataE.setEnabled(false);
                    ftxDataS.setEnabled(true);
                    btnReservar.setEnabled(false);
                    btnLiberar.setEnabled(true);

                }
            }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, 
                "Quarto invalido! Informe um valor numérico inteiro.",
                "Erro de entrada", JOptionPane.ERROR_MESSAGE);
                txtCodigo.requestFocus();
                return;
         }

    }//GEN-LAST:event_btnPesquisaSituacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRegistro().setVisible(true);
            }
        });
    }
    
    private PreparaConexao prepcon =null;
    private Registro registro = null;
    private DaoRegistro daoRegistro = null;
    private Hospede hospede = null;
    private Recepcionista recepcionista = null;
    private Quarto quarto = null;
    private ArrayList<Registro> registros;
    private int posRegistro;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnPesquisaCPF;
    private javax.swing.JButton btnPesquisaReg;
    private javax.swing.JButton btnPesquisaSituacao;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftxCPF;
    private javax.swing.JFormattedTextField ftxDataE;
    private javax.swing.JFormattedTextField ftxDataS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblValHospedagem;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNQuarto;
    private javax.swing.JTextField txtReg;
    // End of variables declaration//GEN-END:variables
}
